#!/bin/bash

apt update && apt upgrade -y && apt install portsentry -y
cat /root/initial-setup/sshd_config > /etc/ssh/sshd_config
cp -R /root/initial-setup/sshd_config.d /etc/ssh/
cp -R /root/initial-setup/keys /etc/ssh/

cat /root/initial-setup/portsentry.conf > /etc/portsentry/portsentry.conf

systemctl restart ssh
systemctl restart portsentry

cat /root/initial-setup/.git-prompt.sh > /root/.git-prompt.sh
cat /root/initial-setup/.bash_aliases > /root/.bash_aliases

source /root/.bash_aliases
