#!/bin/bash

apt-get install software-properties-common
add-apt-repository ppa:ondrej/php
apt-get update

apt-get install php7.1 php7.1-imap php7.1-http php7.1-mongodb php7.1-uuid php7.1-xml php7.1-xmlrpc php7.1-cli php7.1-common php7.1-json php7.1-opcache php7.1-mysql php7.1-mbstring php7.1-mcrypt php7.1-zip php7.1-fpm php7.1-gd php7.1-xdebug php7.1-bcmath php7.1-json php7.1-curl php7.1-dom  -y

